### ISSUE TITLE
Avoid duplication of randomly selected value

### ISSUE THREAD

**Issue by jericho-music** [piercus/hasard#3]
A nice feature would be to remove a value from an array once selected so that it does not get selected again. This would avoid having duplicated values in a randomly generated list.

**Comment by piercus** [comment]
Hello @jericho-music thanks for your feedback.

Have you tried something like this :
```js
const choices = ["a", "b", "c"]
const random1 = h.value(choices)
const ref1 = h.reference(random1);

const antiChoicesFn = h.fn((a) => {
        const index = choices.indexOf(a);
        const remaining = choices.slice(index, index+1)
	return remaining;
});

const differentValues = h.array([
  ref1,
  h.value(antiChoicesFn(ref1))
]);

differentValues.run(1);
```

However, i cannot test right now, so maybe i missed something here.

If working, i'm aware this is not 100% elegant and i'm really open to suggestion on how to add a more elegant shortcut for this.

**Comment by jericho-music** [comment]
Thanks piercus, here is what I got:

```
/node_modules/hasard/lib/hasard/abstract.js:40
        prng() {
            ^

RangeError: Maximum call stack size exceeded
    at ValueHasard.prng (/node_modules/hasard/lib/hasard/abstract.js:40:6)
    at ValueHasard.prng (/node_modules/hasard/lib/hasard/abstract.js:41:28)
    .
    .
```

I was actually wondering about how you control depth (even in the example where a RandomValue refers to randomObject ad infinitum)

BTW, thanks for creating this. I normally would debug more, but am learning javascript so some of this is quite new to me.

**Comment by piercus** [comment]
Hello @jericho-music,

This should be fixed in https://github.com/piercus/hasard/releases/tag/v1.6.0

**Comment by jericho-music** [comment]
This solves the problem if you are creating two values, but will start to get complicated when you want to generate multiple values. I will open another issue with an alternative proposal.
