### ISSUE TITLE
Allow use of getter syntax

### ISSUE THREAD

**Issue by jericho-music** [piercus/hasard#4]
It would be nice to be able to do this:

```
let user = h.object({
  first_name: h.value(first_names),
  last_name: h.value(last_names),
  get email() {
    this.first_name + '.' + this.last_name + '@dfskdfjslfdks.com'
  }
});
```

**Comment by piercus** [comment]
@jericho-music thank for the suggestion

I feel the need is ambigious, and this synthax could lead to 2 different results

## A. Create a getter in the outside object

This can be done with 
```javascript
let user = h.object({
  first_name: h.value(first_names),
  last_name: h.value(last_names)
});

const instance = user.runOnce(1)

Object.defineProperty(instance, 'email', {
  get : function () {return this.first_name + '.' + this.last_name + '@dfskdfjslfdks.com'}
});

```

## B. Interpret the getter into the hasard workflow

This can be done with 
```javascript
const first_name = h.reference(h.value(first_names));
const last_name = h.reference(h.value(last_names));

const email = h.fn((f,l) => f + '.' + l + '@dfskdfjslfdks.com')(first_name, last_name);

let user = h.object({
  first_name,
  last_name,
  email
});

const instance = user.runOnce(1);
```

Which is equivalent to the more compact version
```js
const first_name = h.reference(h.value(first_names));
const last_name = h.reference(h.value(last_names));

let user = h.object({
  first_name,
  last_name,
  email: h.add(first_name, last_name)
});

const instance = user.runOnce(1);
```

## A vs B

A. is more about "object decoration" and i feel is not related to hasard, and should be done after the hasard workflow by the user, and B. is already feasible with current hasard suite.

Anyway the need is ambiguous here

About B. there might be lot of things to improve in the documentation/guide for new users, so please feel free to suggest any improvement.

I've created shortcuts (h.add, h.if ...) to lighten the synthax and avoid using h.fn each time
