### ISSUE TITLE
New feature: Maybe add another object h.stack(...) to avoid re-use of random generated value.

### ISSUE THREAD

**Issue by jericho-music** [piercus/hasard#7]
Based on the discussion for avoiding reuse of random generated value, the following was proposed and implemented:

```
	const choices = ['a', 'b', 'c'];
	const random1 = hasard.value(choices);
	const ref1 = hasard.reference(random1);

	const antiChoicesFn = hasard.fn(a => {
		const index = choices.indexOf(a);
		const remaining = choices.slice(0, index).concat(choices.slice(index + 1));
		return remaining;
	});

	const differentValues = hasard.array([
		ref1,
		hasard.value(antiChoicesFn(ref1))
	]);
```

Catch with this is that generating x number of values (where x > 2) will make this complicated.

Another option to think about is to add a ```stack``` object. This object gets reshuffled at the start of the run and then a value gets popped off for each run. This will guarantee that an object is never reused and allow multiple pops without needing to pass a used value reference. One could also make the shuffle algorithm used in the beginning a property that can be configured.

Code might look something like this:

```
const choices = ['a', 'b', 'c'];
const random1 = hasard.stack(choices)

const differentValues = hasard.array([random1, random1, random1]);
```

**Comment by piercus** [comment]
Hello @jericho-music 
Thanks for this proposal.

I suggest something like this
```js
// choose 2 out of 3
const v = h.sample({
	choices: ['a', 'b', 'c'],
	size: 2
});

// random order of ['a', 'b', 'c']

const v = h.sample({
	choices: ['a', 'b', 'c'],
	size: 3
});

// raise an error

const v = h.sample({
	choices: ['a', 'b', 'c'],
	size: 4
});

// => raise an error 'choices.length (3) < size (4)'
```

Please confirm it will fullfill your needs

**Comment by piercus** [comment]
Hello @jericho-music,

after checking the code, i think that 

```js
const differentValues = hasard.array({
  values: choices,
  size: 3,
  randomOrder: true
});
```
should work for this.

See https://github.com/piercus/hasard#harrayvalues-arrayhasard-size-hasardinteger-randomorder-hasardboolean---hasardarray

**Comment by jericho-music** [comment]
Yes, that will do the trick. Thanks for working this through with me.

**Comment by jericho-music** [comment]
Hmmm...I just had a repeat with randomOrder: true. Let me see if I can create a smaller reproducible case.

**Comment by jericho-music** [comment]
Never mind, user error. I was using h.value instead of passing the input array directly. That does make a difference in providing repeats again.

**Comment by jericho-music** [comment]
I am not sure what the expected behavior of this is supposed to be:

```
const v = h.array({                                                                                                                                  
   values: ['aa', 'bb', 'cc', 'dd', 'ee', 'ff', 'gg', 'hh'],                                                                                          
   size: h.integer(0, 3),                                                                                                                             
   randomOrder: true                                                                                                                                  
 });
```

My thinking is that it would return a random size (between 0 and 3) array of randomly selected items. But the size of the array returned can be outside the range asked for. Here is a run:

```
  [
    'bb', 'hh', 'aa',
    'gg', 'cc', 'dd',
    'ff', 'ee'
  ],
  [ 'gg', 'cc' ],
  [ 'ff', 'aa' ],
  [
    'bb', 'hh', 'ee',
    'gg', 'ff', 'cc',
    'aa', 'dd'
  ],
```

**Comment by piercus** [comment]
@jericho-music yes this is an issue :-)

**Comment by piercus** [comment]
New issue created in https://github.com/piercus/hasard/issues/8

**Comment by piercus** [comment]
Fixed, see https://github.com/piercus/hasard/issues/8#issuecomment-605108854

Thanks a lot for your help and feedbacks

**Comment by jericho-music** [comment]
Brilliant. Thanks.
